// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TestMessage1.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ChimeApp.Models {

  /// <summary>Holder for reflection information generated from TestMessage1.proto</summary>
  public static partial class TestMessage1Reflection {

    #region Descriptor
    /// <summary>File descriptor for TestMessage1.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestMessage1Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJUZXN0TWVzc2FnZTEucHJvdG8SD0NoaW1lQXBwLk1vZGVscxoVVmFsaWRh",
            "dGlvblJ1bGVzLnByb3RvGh5nb29nbGUvcHJvdG9idWYvd3JhcHBlcnMucHJv",
            "dG8i1gIKDFRlc3RNZXNzYWdlMRJMCgpUZXN0U3RyaW5nGAEgASgLMhwuZ29v",
            "Z2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlQhqatRgCCAGitRgCCAqqtRgKCghe",
            "WzAtOV0qJBJECgtUZXN0SW50ZWdlchgCIAEoCzIbLmdvb2dsZS5wcm90b2J1",
            "Zi5JbnQzMlZhbHVlQhKKtRgCCAqStRgCCAGatRgCCAESNAoOVGVzdFN0cmlu",
            "Z0xpc3QYAyADKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSOwoO",
            "VGVzdFN1Yk1lc3NhZ2UYBCABKAsyGy5DaGltZUFwcC5Nb2RlbHMuU3ViTWVz",
            "c2FnZUIGmrUYAggBEj8KElRlc3RTdWJNZXNzYWdlTGlzdBgFIAMoCzIbLkNo",
            "aW1lQXBwLk1vZGVscy5TdWJNZXNzYWdlQgaatRgCCAEiQgoKU3ViTWVzc2Fn",
            "ZRI0CghUZXN0Qm9vbBgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5Cb29sVmFs",
            "dWVCBpq1GAIIAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ChimeApp.Models.ValidationRulesReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ChimeApp.Models.TestMessage1), global::ChimeApp.Models.TestMessage1.Parser, new[]{ "TestString", "TestInteger", "TestStringList", "TestSubMessage", "TestSubMessageList" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ChimeApp.Models.SubMessage), global::ChimeApp.Models.SubMessage.Parser, new[]{ "TestBool" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TestMessage1 : pb::IMessage<TestMessage1>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TestMessage1> _parser = new pb::MessageParser<TestMessage1>(() => new TestMessage1());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TestMessage1> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChimeApp.Models.TestMessage1Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMessage1() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMessage1(TestMessage1 other) : this() {
      TestString = other.TestString;
      TestInteger = other.TestInteger;
      testStringList_ = other.testStringList_.Clone();
      testSubMessage_ = other.testSubMessage_ != null ? other.testSubMessage_.Clone() : null;
      testSubMessageList_ = other.testSubMessageList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMessage1 Clone() {
      return new TestMessage1(this);
    }

    /// <summary>Field number for the "TestString" field.</summary>
    public const int TestStringFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _single_testString_codec = pb::FieldCodec.ForClassWrapper<string>(10);
    private string testString_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TestString {
      get { return testString_; }
      set {
        testString_ = value;
      }
    }


    /// <summary>Field number for the "TestInteger" field.</summary>
    public const int TestIntegerFieldNumber = 2;
    private static readonly pb::FieldCodec<int?> _single_testInteger_codec = pb::FieldCodec.ForStructWrapper<int>(18);
    private int? testInteger_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int? TestInteger {
      get { return testInteger_; }
      set {
        testInteger_ = value;
      }
    }


    /// <summary>Field number for the "TestStringList" field.</summary>
    public const int TestStringListFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_testStringList_codec
        = pb::FieldCodec.ForClassWrapper<string>(26);
    private readonly pbc::RepeatedField<string> testStringList_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> TestStringList {
      get { return testStringList_; }
    }

    /// <summary>Field number for the "TestSubMessage" field.</summary>
    public const int TestSubMessageFieldNumber = 4;
    private global::ChimeApp.Models.SubMessage testSubMessage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ChimeApp.Models.SubMessage TestSubMessage {
      get { return testSubMessage_; }
      set {
        testSubMessage_ = value;
      }
    }

    /// <summary>Field number for the "TestSubMessageList" field.</summary>
    public const int TestSubMessageListFieldNumber = 5;
    private static readonly pb::FieldCodec<global::ChimeApp.Models.SubMessage> _repeated_testSubMessageList_codec
        = pb::FieldCodec.ForMessage(42, global::ChimeApp.Models.SubMessage.Parser);
    private readonly pbc::RepeatedField<global::ChimeApp.Models.SubMessage> testSubMessageList_ = new pbc::RepeatedField<global::ChimeApp.Models.SubMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ChimeApp.Models.SubMessage> TestSubMessageList {
      get { return testSubMessageList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TestMessage1);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TestMessage1 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TestString != other.TestString) return false;
      if (TestInteger != other.TestInteger) return false;
      if(!testStringList_.Equals(other.testStringList_)) return false;
      if (!object.Equals(TestSubMessage, other.TestSubMessage)) return false;
      if(!testSubMessageList_.Equals(other.testSubMessageList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (testString_ != null) hash ^= TestString.GetHashCode();
      if (testInteger_ != null) hash ^= TestInteger.GetHashCode();
      hash ^= testStringList_.GetHashCode();
      if (testSubMessage_ != null) hash ^= TestSubMessage.GetHashCode();
      hash ^= testSubMessageList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (testString_ != null) {
        _single_testString_codec.WriteTagAndValue(output, TestString);
      }
      if (testInteger_ != null) {
        _single_testInteger_codec.WriteTagAndValue(output, TestInteger);
      }
      testStringList_.WriteTo(output, _repeated_testStringList_codec);
      if (testSubMessage_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(TestSubMessage);
      }
      testSubMessageList_.WriteTo(output, _repeated_testSubMessageList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (testString_ != null) {
        _single_testString_codec.WriteTagAndValue(ref output, TestString);
      }
      if (testInteger_ != null) {
        _single_testInteger_codec.WriteTagAndValue(ref output, TestInteger);
      }
      testStringList_.WriteTo(ref output, _repeated_testStringList_codec);
      if (testSubMessage_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(TestSubMessage);
      }
      testSubMessageList_.WriteTo(ref output, _repeated_testSubMessageList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (testString_ != null) {
        size += _single_testString_codec.CalculateSizeWithTag(TestString);
      }
      if (testInteger_ != null) {
        size += _single_testInteger_codec.CalculateSizeWithTag(TestInteger);
      }
      size += testStringList_.CalculateSize(_repeated_testStringList_codec);
      if (testSubMessage_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TestSubMessage);
      }
      size += testSubMessageList_.CalculateSize(_repeated_testSubMessageList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TestMessage1 other) {
      if (other == null) {
        return;
      }
      if (other.testString_ != null) {
        if (testString_ == null || other.TestString != "") {
          TestString = other.TestString;
        }
      }
      if (other.testInteger_ != null) {
        if (testInteger_ == null || other.TestInteger != 0) {
          TestInteger = other.TestInteger;
        }
      }
      testStringList_.Add(other.testStringList_);
      if (other.testSubMessage_ != null) {
        if (testSubMessage_ == null) {
          TestSubMessage = new global::ChimeApp.Models.SubMessage();
        }
        TestSubMessage.MergeFrom(other.TestSubMessage);
      }
      testSubMessageList_.Add(other.testSubMessageList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            string value = _single_testString_codec.Read(input);
            if (testString_ == null || value != "") {
              TestString = value;
            }
            break;
          }
          case 18: {
            int? value = _single_testInteger_codec.Read(input);
            if (testInteger_ == null || value != 0) {
              TestInteger = value;
            }
            break;
          }
          case 26: {
            testStringList_.AddEntriesFrom(input, _repeated_testStringList_codec);
            break;
          }
          case 34: {
            if (testSubMessage_ == null) {
              TestSubMessage = new global::ChimeApp.Models.SubMessage();
            }
            input.ReadMessage(TestSubMessage);
            break;
          }
          case 42: {
            testSubMessageList_.AddEntriesFrom(input, _repeated_testSubMessageList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            string value = _single_testString_codec.Read(ref input);
            if (testString_ == null || value != "") {
              TestString = value;
            }
            break;
          }
          case 18: {
            int? value = _single_testInteger_codec.Read(ref input);
            if (testInteger_ == null || value != 0) {
              TestInteger = value;
            }
            break;
          }
          case 26: {
            testStringList_.AddEntriesFrom(ref input, _repeated_testStringList_codec);
            break;
          }
          case 34: {
            if (testSubMessage_ == null) {
              TestSubMessage = new global::ChimeApp.Models.SubMessage();
            }
            input.ReadMessage(TestSubMessage);
            break;
          }
          case 42: {
            testSubMessageList_.AddEntriesFrom(ref input, _repeated_testSubMessageList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SubMessage : pb::IMessage<SubMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SubMessage> _parser = new pb::MessageParser<SubMessage>(() => new SubMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SubMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChimeApp.Models.TestMessage1Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SubMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SubMessage(SubMessage other) : this() {
      TestBool = other.TestBool;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SubMessage Clone() {
      return new SubMessage(this);
    }

    /// <summary>Field number for the "TestBool" field.</summary>
    public const int TestBoolFieldNumber = 1;
    private static readonly pb::FieldCodec<bool?> _single_testBool_codec = pb::FieldCodec.ForStructWrapper<bool>(10);
    private bool? testBool_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool? TestBool {
      get { return testBool_; }
      set {
        testBool_ = value;
      }
    }


    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SubMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SubMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TestBool != other.TestBool) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (testBool_ != null) hash ^= TestBool.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (testBool_ != null) {
        _single_testBool_codec.WriteTagAndValue(output, TestBool);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (testBool_ != null) {
        _single_testBool_codec.WriteTagAndValue(ref output, TestBool);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (testBool_ != null) {
        size += _single_testBool_codec.CalculateSizeWithTag(TestBool);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SubMessage other) {
      if (other == null) {
        return;
      }
      if (other.testBool_ != null) {
        if (testBool_ == null || other.TestBool != false) {
          TestBool = other.TestBool;
        }
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            bool? value = _single_testBool_codec.Read(input);
            if (testBool_ == null || value != false) {
              TestBool = value;
            }
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            bool? value = _single_testBool_codec.Read(ref input);
            if (testBool_ == null || value != false) {
              TestBool = value;
            }
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
