// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TestMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ChimeAppTest {

  /// <summary>Holder for reflection information generated from TestMessage.proto</summary>
  public static partial class TestMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for TestMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFUZXN0TWVzc2FnZS5wcm90bxIMQ2hpbWVBcHBUZXN0Gh5nb29nbGUvcHJv",
            "dG9idWYvd3JhcHBlcnMucHJvdG8aFVZhbGlkYXRpb25SdWxlcy5wcm90byLd",
            "AQoLVGVzdE1lc3NhZ2USKgoEU3RyMRgBIAEoCzIcLmdvb2dsZS5wcm90b2J1",
            "Zi5TdHJpbmdWYWx1ZRIyCgRTdHIyGAIgASgLMhwuZ29vZ2xlLnByb3RvYnVm",
            "LlN0cmluZ1ZhbHVlQgaatRgCCAESMgoEU3RyMxgDIAEoCzIcLmdvb2dsZS5w",
            "cm90b2J1Zi5TdHJpbmdWYWx1ZUIGorUYAggKEjoKBFN0cjQYBCABKAsyHC5n",
            "b29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWVCDqq1GAoKCF5bMC05XSskYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::ChimeAppTest.ValidationRulesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ChimeAppTest.TestMessage), global::ChimeAppTest.TestMessage.Parser, new[]{ "Str1", "Str2", "Str3", "Str4" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TestMessage : pb::IMessage<TestMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TestMessage> _parser = new pb::MessageParser<TestMessage>(() => new TestMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TestMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChimeAppTest.TestMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMessage(TestMessage other) : this() {
      Str1 = other.Str1;
      Str2 = other.Str2;
      Str3 = other.Str3;
      Str4 = other.Str4;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMessage Clone() {
      return new TestMessage(this);
    }

    /// <summary>Field number for the "Str1" field.</summary>
    public const int Str1FieldNumber = 1;
    private static readonly pb::FieldCodec<string> _single_str1_codec = pb::FieldCodec.ForClassWrapper<string>(10);
    private string str1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Str1 {
      get { return str1_; }
      set {
        str1_ = value;
      }
    }


    /// <summary>Field number for the "Str2" field.</summary>
    public const int Str2FieldNumber = 2;
    private static readonly pb::FieldCodec<string> _single_str2_codec = pb::FieldCodec.ForClassWrapper<string>(18);
    private string str2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Str2 {
      get { return str2_; }
      set {
        str2_ = value;
      }
    }


    /// <summary>Field number for the "Str3" field.</summary>
    public const int Str3FieldNumber = 3;
    private static readonly pb::FieldCodec<string> _single_str3_codec = pb::FieldCodec.ForClassWrapper<string>(26);
    private string str3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Str3 {
      get { return str3_; }
      set {
        str3_ = value;
      }
    }


    /// <summary>Field number for the "Str4" field.</summary>
    public const int Str4FieldNumber = 4;
    private static readonly pb::FieldCodec<string> _single_str4_codec = pb::FieldCodec.ForClassWrapper<string>(34);
    private string str4_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Str4 {
      get { return str4_; }
      set {
        str4_ = value;
      }
    }


    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TestMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TestMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Str1 != other.Str1) return false;
      if (Str2 != other.Str2) return false;
      if (Str3 != other.Str3) return false;
      if (Str4 != other.Str4) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (str1_ != null) hash ^= Str1.GetHashCode();
      if (str2_ != null) hash ^= Str2.GetHashCode();
      if (str3_ != null) hash ^= Str3.GetHashCode();
      if (str4_ != null) hash ^= Str4.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (str1_ != null) {
        _single_str1_codec.WriteTagAndValue(output, Str1);
      }
      if (str2_ != null) {
        _single_str2_codec.WriteTagAndValue(output, Str2);
      }
      if (str3_ != null) {
        _single_str3_codec.WriteTagAndValue(output, Str3);
      }
      if (str4_ != null) {
        _single_str4_codec.WriteTagAndValue(output, Str4);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (str1_ != null) {
        _single_str1_codec.WriteTagAndValue(ref output, Str1);
      }
      if (str2_ != null) {
        _single_str2_codec.WriteTagAndValue(ref output, Str2);
      }
      if (str3_ != null) {
        _single_str3_codec.WriteTagAndValue(ref output, Str3);
      }
      if (str4_ != null) {
        _single_str4_codec.WriteTagAndValue(ref output, Str4);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (str1_ != null) {
        size += _single_str1_codec.CalculateSizeWithTag(Str1);
      }
      if (str2_ != null) {
        size += _single_str2_codec.CalculateSizeWithTag(Str2);
      }
      if (str3_ != null) {
        size += _single_str3_codec.CalculateSizeWithTag(Str3);
      }
      if (str4_ != null) {
        size += _single_str4_codec.CalculateSizeWithTag(Str4);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TestMessage other) {
      if (other == null) {
        return;
      }
      if (other.str1_ != null) {
        if (str1_ == null || other.Str1 != "") {
          Str1 = other.Str1;
        }
      }
      if (other.str2_ != null) {
        if (str2_ == null || other.Str2 != "") {
          Str2 = other.Str2;
        }
      }
      if (other.str3_ != null) {
        if (str3_ == null || other.Str3 != "") {
          Str3 = other.Str3;
        }
      }
      if (other.str4_ != null) {
        if (str4_ == null || other.Str4 != "") {
          Str4 = other.Str4;
        }
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            string value = _single_str1_codec.Read(input);
            if (str1_ == null || value != "") {
              Str1 = value;
            }
            break;
          }
          case 18: {
            string value = _single_str2_codec.Read(input);
            if (str2_ == null || value != "") {
              Str2 = value;
            }
            break;
          }
          case 26: {
            string value = _single_str3_codec.Read(input);
            if (str3_ == null || value != "") {
              Str3 = value;
            }
            break;
          }
          case 34: {
            string value = _single_str4_codec.Read(input);
            if (str4_ == null || value != "") {
              Str4 = value;
            }
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            string value = _single_str1_codec.Read(ref input);
            if (str1_ == null || value != "") {
              Str1 = value;
            }
            break;
          }
          case 18: {
            string value = _single_str2_codec.Read(ref input);
            if (str2_ == null || value != "") {
              Str2 = value;
            }
            break;
          }
          case 26: {
            string value = _single_str3_codec.Read(ref input);
            if (str3_ == null || value != "") {
              Str3 = value;
            }
            break;
          }
          case 34: {
            string value = _single_str4_codec.Read(ref input);
            if (str4_ == null || value != "") {
              Str4 = value;
            }
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
