// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CreateMeeting.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ChimeApp.Models {

  /// <summary>Holder for reflection information generated from CreateMeeting.proto</summary>
  public static partial class CreateMeetingReflection {

    #region Descriptor
    /// <summary>File descriptor for CreateMeeting.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CreateMeetingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNDcmVhdGVNZWV0aW5nLnByb3RvEg9DaGltZUFwcC5Nb2RlbHMaFVZhbGlk",
            "YXRpb25SdWxlcy5wcm90byKOAQoUQ3JlYXRlTWVldGluZ1JlcXVlc3QSKAoR",
            "RXh0ZXJuYWxNZWV0aW5nSWQYASABKAlCDZq1GAIIAaK1GAMI/wESKQoSRXh0",
            "ZXJuYWxBdHRlbmRlZUlkGAIgASgJQg2atRgCCAGitRgDCP8BEiEKC01heEF0",
            "dGVuZGVlGAMgASgFQgyKtRgCCBSStRgCCAEiQgoVQ3JlYXRlTWVldGluZ1Jl",
            "c3BvbnNlEhMKC01lZXRpbmdJbmZvGAEgASgJEhQKDEF0dGVuZGVlSW5mbxgC",
            "IAEoCWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ChimeApp.Models.ValidationRulesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ChimeApp.Models.CreateMeetingRequest), global::ChimeApp.Models.CreateMeetingRequest.Parser, new[]{ "ExternalMeetingId", "ExternalAttendeeId", "MaxAttendee" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ChimeApp.Models.CreateMeetingResponse), global::ChimeApp.Models.CreateMeetingResponse.Parser, new[]{ "MeetingInfo", "AttendeeInfo" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CreateMeetingRequest : pb::IMessage<CreateMeetingRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateMeetingRequest> _parser = new pb::MessageParser<CreateMeetingRequest>(() => new CreateMeetingRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CreateMeetingRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChimeApp.Models.CreateMeetingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateMeetingRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateMeetingRequest(CreateMeetingRequest other) : this() {
      externalMeetingId_ = other.externalMeetingId_;
      externalAttendeeId_ = other.externalAttendeeId_;
      maxAttendee_ = other.maxAttendee_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateMeetingRequest Clone() {
      return new CreateMeetingRequest(this);
    }

    /// <summary>Field number for the "ExternalMeetingId" field.</summary>
    public const int ExternalMeetingIdFieldNumber = 1;
    private string externalMeetingId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ExternalMeetingId {
      get { return externalMeetingId_; }
      set {
        externalMeetingId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ExternalAttendeeId" field.</summary>
    public const int ExternalAttendeeIdFieldNumber = 2;
    private string externalAttendeeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ExternalAttendeeId {
      get { return externalAttendeeId_; }
      set {
        externalAttendeeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "MaxAttendee" field.</summary>
    public const int MaxAttendeeFieldNumber = 3;
    private int maxAttendee_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxAttendee {
      get { return maxAttendee_; }
      set {
        maxAttendee_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CreateMeetingRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CreateMeetingRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ExternalMeetingId != other.ExternalMeetingId) return false;
      if (ExternalAttendeeId != other.ExternalAttendeeId) return false;
      if (MaxAttendee != other.MaxAttendee) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ExternalMeetingId.Length != 0) hash ^= ExternalMeetingId.GetHashCode();
      if (ExternalAttendeeId.Length != 0) hash ^= ExternalAttendeeId.GetHashCode();
      if (MaxAttendee != 0) hash ^= MaxAttendee.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ExternalMeetingId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ExternalMeetingId);
      }
      if (ExternalAttendeeId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ExternalAttendeeId);
      }
      if (MaxAttendee != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MaxAttendee);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ExternalMeetingId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ExternalMeetingId);
      }
      if (ExternalAttendeeId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ExternalAttendeeId);
      }
      if (MaxAttendee != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MaxAttendee);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ExternalMeetingId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExternalMeetingId);
      }
      if (ExternalAttendeeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExternalAttendeeId);
      }
      if (MaxAttendee != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxAttendee);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CreateMeetingRequest other) {
      if (other == null) {
        return;
      }
      if (other.ExternalMeetingId.Length != 0) {
        ExternalMeetingId = other.ExternalMeetingId;
      }
      if (other.ExternalAttendeeId.Length != 0) {
        ExternalAttendeeId = other.ExternalAttendeeId;
      }
      if (other.MaxAttendee != 0) {
        MaxAttendee = other.MaxAttendee;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ExternalMeetingId = input.ReadString();
            break;
          }
          case 18: {
            ExternalAttendeeId = input.ReadString();
            break;
          }
          case 24: {
            MaxAttendee = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ExternalMeetingId = input.ReadString();
            break;
          }
          case 18: {
            ExternalAttendeeId = input.ReadString();
            break;
          }
          case 24: {
            MaxAttendee = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CreateMeetingResponse : pb::IMessage<CreateMeetingResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateMeetingResponse> _parser = new pb::MessageParser<CreateMeetingResponse>(() => new CreateMeetingResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CreateMeetingResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ChimeApp.Models.CreateMeetingReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateMeetingResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateMeetingResponse(CreateMeetingResponse other) : this() {
      meetingInfo_ = other.meetingInfo_;
      attendeeInfo_ = other.attendeeInfo_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateMeetingResponse Clone() {
      return new CreateMeetingResponse(this);
    }

    /// <summary>Field number for the "MeetingInfo" field.</summary>
    public const int MeetingInfoFieldNumber = 1;
    private string meetingInfo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MeetingInfo {
      get { return meetingInfo_; }
      set {
        meetingInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AttendeeInfo" field.</summary>
    public const int AttendeeInfoFieldNumber = 2;
    private string attendeeInfo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AttendeeInfo {
      get { return attendeeInfo_; }
      set {
        attendeeInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CreateMeetingResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CreateMeetingResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MeetingInfo != other.MeetingInfo) return false;
      if (AttendeeInfo != other.AttendeeInfo) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MeetingInfo.Length != 0) hash ^= MeetingInfo.GetHashCode();
      if (AttendeeInfo.Length != 0) hash ^= AttendeeInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MeetingInfo.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MeetingInfo);
      }
      if (AttendeeInfo.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AttendeeInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MeetingInfo.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MeetingInfo);
      }
      if (AttendeeInfo.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AttendeeInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MeetingInfo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MeetingInfo);
      }
      if (AttendeeInfo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AttendeeInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CreateMeetingResponse other) {
      if (other == null) {
        return;
      }
      if (other.MeetingInfo.Length != 0) {
        MeetingInfo = other.MeetingInfo;
      }
      if (other.AttendeeInfo.Length != 0) {
        AttendeeInfo = other.AttendeeInfo;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MeetingInfo = input.ReadString();
            break;
          }
          case 18: {
            AttendeeInfo = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MeetingInfo = input.ReadString();
            break;
          }
          case 18: {
            AttendeeInfo = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
